DROP TABLE IF EXISTS CUSTOMER;
CREATE TABLE CUSTOMER (
id INT AUTO_INCREMENT NOT NULL,
name VARCHAR(50) NOT NULL,
surname VARCHAR(50) NOT NULL,
email VARCHAR(50) NOT NULL,
PRIMARY KEY (id)
);

DROP TABLE IF EXISTS BOOK;
CREATE TABLE BOOK (
id INT AUTO_INCREMENT  PRIMARY KEY,
bookName VARCHAR(50) NOT NULL,
author VARCHAR(50) NOT NULL,
price DECIMAL(10,3) NOT NULL,
bookCount INT NOT NULL
);

DROP TABLE IF EXISTS ORDERS;
CREATE TABLE ORDERS (
id INT AUTO_INCREMENT PRIMARY KEY,
bookName VARCHAR(50) NOT NULL,
customerId INT NOT NULL,
orderCount INT NOT NULL,
orderAmount DECIMAL(10,3) NOT NULL,
orderStatus VARCHAR(10) NOT NULL,
orderDate TIMESTAMP NOT NULL
);